//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeDevPnP.TimerService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OfficeDevPnP.TimerService.ApplicationStrings", typeof(ApplicationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerating Jobs.
        /// </summary>
        internal static string EnumeratingJobs {
            get {
                return ResourceManager.GetString("EnumeratingJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Job &quot;{0}&quot; ({1}).
        /// </summary>
        internal static string FinishedJob0_1 {
            get {
                return ResourceManager.GetString("FinishedJob0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPOTIMERSERVICE.
        /// </summary>
        internal static string ServiceIndentifier {
            get {
                return ResourceManager.GetString("ServiceIndentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Job &quot;{0}&quot;({1}).
        /// </summary>
        internal static string StartingJob0_1 {
            get {
                return ResourceManager.GetString("StartingJob0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting service.
        /// </summary>
        internal static string StartingService {
            get {
                return ResourceManager.GetString("StartingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting service.
        /// </summary>
        internal static string StoppingService {
            get {
                return ResourceManager.GetString("StoppingService", resourceCulture);
            }
        }
    }
}
